# PlatformIO pre:script — writes include/build_version.h on every build.
# Version string: git describe (tags) or short SHA; "-dirty" if working tree not clean.
from __future__ import annotations

import subprocess
import time
from pathlib import Path

Import("env")  # noqa: F821 — provided by SCons when PlatformIO loads this file


def _run_git(project_dir: Path, *args: str) -> str:
    try:
        return subprocess.check_output(
            ["git", *args],
            cwd=project_dir,
            stderr=subprocess.DEVNULL,
            text=True,
        ).strip()
    except (subprocess.CalledProcessError, FileNotFoundError, OSError):
        return ""


def _c_escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"')


def generate(project_dir: Path) -> None:
    include_dir = project_dir / "include"
    include_dir.mkdir(parents=True, exist_ok=True)
    out_path = include_dir / "build_version.h"

    tag = _run_git(project_dir, "describe", "--tags", "--always", "--dirty", "HEAD")
    if not tag:
        tag = _run_git(project_dir, "rev-parse", "--short", "HEAD") or "nogit"

    short = _run_git(project_dir, "rev-parse", "--short", "HEAD") or "nogit"
    build_unix = int(time.time())

    lines = [
        "#pragma once",
        "// Generated by scripts/gen_build_version.py — do not edit by hand.",
        f'#define MEDALERT_FW_VERSION "{_c_escape(tag)}"',
        f'#define MEDALERT_FW_GIT "{_c_escape(short)}"',
        f"#define MEDALERT_FW_BUILD_UNIX {build_unix}ULL",
        "",
    ]
    text = "\n".join(lines)

    if out_path.is_file() and out_path.read_text(encoding="utf-8") == text:
        return
    out_path.write_text(text, encoding="utf-8")
    print("[gen_build_version] wrote", out_path)


generate(Path(env["PROJECT_DIR"]))  # noqa: F821
